week11/CourseManagement/config/routes.rb
Rails.application.routes.draw do

  resources :lectures do
    resources :tasks do
      resources :solutions
    end
  end

end

week11/CourseManagement/app/models/lecture.rb
class Lecture < ActiveRecord::Base
  validates :name, presence: true
  validates :body, presence: true

  has_many :tasks, :dependent => :destroy
end

week11/CourseManagement/app/models/solution.rb
class Solution < ActiveRecord::Base
  validates :answer, presence: true

  belongs_to :task

  scope :for_task, -> task { Solution.where(task_id: task) }
end

week11/CourseManagement/app/models/task.rb
class Task < ActiveRecord::Base
  validates :name, presence: true
  validates :description, presence: true

  belongs_to :lecture
  has_many :solutions, :dependent => :destroy

  scope :for_lecture, -> (lecture) { Task.where(lecture_id: lecture) }
end

week11/CourseManagement/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

week11/CourseManagement/app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  def index
    @lectures = Lecture.all
  end

  def new
    @lecture = Lecture.new
  end

  def create
    @lecture = Lecture.new(lecture_params)

    if @lecture.save
      redirect_to @lecture, notice: 'Lecture was successfully created.'
    else
      render :new
    end
  end

  def edit
    @lecture = find_lecture
  end

  def show
    @lecture = find_lecture
  end

  def update
    @lecture = find_lecture

    if @lecture.update(lecture_params)
      redirect_to @lecture, notice: 'Lecture was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @lecture = find_lecture
    @lecture.destroy

    redirect_to lectures_path, notice: 'Lecture was successfully deleted.'
  end

  private

  def lecture_params
    params.require(:lecture).permit(:name, :body)
  end

  def find_lecture
    Lecture.find(params[:id])
  end
end

week11/CourseManagement/app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController
  def index
    @solutions = Solution.for_task(params[:task_id])
  end

  def create
    @lecture = Lecture.find(params[:lecture_id])
    @lecture.tasks.find(params[:task_id]).solutions.create!(solution_params)

    redirect_to lecture_task_solutions_path(params[:lecture_id], params[:task_id]), notice: "Solution was successfully created."
  end

  def new
    @solution = Solution.new
  end

  def edit
    @solution = Solution.for_task(params[:task_id]).find(params[:id])
  end

  def show
    @solution = Solution.for_task(params[:task_id]).find(params[:id])
  end

  def update
    @lecture = Lecture.find(params[:lecture_id])
    @solution = Solution.for_task(params[:task_id]).find(params[:id])

    if @solution.update(solution_params)
      redirect_to lecture_task_solutions_path(params[:lecture_id], params[:task_id]), notice: 'Solution was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @solution = Solution.for_task(params[:task_id]).find(params[:id])
    @solution.destroy

    redirect_to lecture_task_solutions_path(params[:lecture_id], params[:task_id]), notice: 'Solution was successfully deleted.'
  end

  private

  def solution_params
    params.require(:solution).permit(:answer, :task_id)
  end
end

week11/CourseManagement/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.for_lecture(params[:lecture_id])
  end

  def create
    @task = Lecture.find(params[:lecture_id]).tasks.create!(task_params)

    redirect_to lecture_tasks_path(params[:lecture_id]), notice: 'Task was successfully created.'
  end

  def new
    @task = Task.new
  end

  def edit
    @task = Task.for_lecture(params[:lecture_id]).find(params[:id])
  end

  def show
    @task = Task.for_lecture(params[:lecture_id]).find(params[:id])
  end

  def update
    @task = Task.for_lecture(params[:lecture_id]).find(params[:id])

    if @task.update(task_params)
      redirect_to lecture_tasks_path(params[:lecture_id]), notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @task = Task.for_lecture(params[:lecture_id]).find(params[:id])
    @task.destroy

    redirect_to lecture_tasks_path(params[:lecture_id]), notice: 'Task was successfully deleted.'
  end

  private

  def task_params
    params.require(:task).permit(:name, :description, :lecture_id)
  end
end

week11/CourseManagement/app/helpers/application_helper.rb
module ApplicationHelper
end

week11/CourseManagement/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CourseManagement</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

week11/CourseManagement/app/views/lectures/_form.html.erb
<%= form_for(@lecture) do |f| %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>
  </div> 
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

week11/CourseManagement/app/views/lectures/edit.html.erb
<h1>Editing Lecture</h1>

<%= render 'form' %>

<%= link_to 'Back', lectures_path %>

week11/CourseManagement/app/views/lectures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>List of all lectures</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if @lectures.empty? %>
      <strong> No lectures yet </strong>
    <% else %>
      <% @lectures.each do |lecture| %>
        <tr>
          <td><%= lecture.name %></td>
          <td><%= link_to 'Show', lecture %></td>
          <td><%= link_to 'Edit', edit_lecture_path(lecture) %></td>
          <td><%= link_to 'Destroy', lecture, method: :delete, data: { confirm: 'Are you sure, you cannot restore it!!!' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lecture', new_lecture_path %>
<%= link_to 'Home Page', lectures_path %>

week11/CourseManagement/app/views/lectures/new.html.erb
<h1>New Lecture</h1>

<%= render 'form' %>

<%= link_to 'Back', lectures_path %>

week11/CourseManagement/app/views/lectures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
    <%= @lecture.body %>
</p>

<%= link_to 'Edit', edit_lecture_path(@lecture) %> |
<%= link_to 'Back', lectures_path %>

week11/CourseManagement/app/views/solutions/_form.html.erb
<%= form_for @solution, url: lecture_task_solutions_path(params[:lecture_id], params[:task_id]), method: :post  do |f| %>  
  <div class="field">
    <%= f.label :answer %><br>
    <%= f.text_field :answer %><br>
  </div> 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

week11/CourseManagement/app/views/solutions/edit.html.erb
<h1>Editing Solution</h1>

<%= form_for @solution, url: lecture_task_solution_path(params[:lecture_id], params[:task_id], @solution), method: :put  do |f| %>  
  <div class="field">
    <%= f.label :answer %><br>
    <%= f.text_field :answer %><br>
  </div> 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', lecture_task_solutions_path(params[:lecture_id], params[:task_id]) %>

week11/CourseManagement/app/views/solutions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>List of all solutions for this task</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <% @solutions.each do |solution| %>
        <tr>
          <td><%= solution.answer %></td>
          <td><%= link_to 'Show', lecture_task_solution_path(params[:lecture_id], params[:task_id], solution) %></td>
          <td><%= link_to 'Edit', edit_lecture_task_solution_path(params[:lecture_id], params[:task_id], solution) %></td>
          <td><%= link_to 'Destroy', lecture_task_solution_path(params[:lecture_id], params[:task_id], solution), method: :delete, data: { confirm: 'Are you sure, you cannot restore it!!!' } %></td>
        </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Solution', new_lecture_task_solution_path(params[:lecture_id], params[:task_id]) %>
<%= link_to 'Home Page', lectures_path %>

week11/CourseManagement/app/views/solutions/new.html.erb
<h1>New Solution</h1>

<%= render 'form' %>

<%= link_to 'Back', lecture_task_solutions_path(params[:lecture_id], params[:task_id]) %>

week11/CourseManagement/app/views/solutions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
    <%= @solution.answer %>
</p>

<%= link_to 'Edit', edit_lecture_task_solution_path(params[:lecture_id], params[:task_id], @solution) %> |
<%= link_to 'Back', lecture_task_solutions_path(params[:lecture_id], params[:task_id]) %>

week11/CourseManagement/app/views/tasks/_form.html.erb
<%= form_for @task, url: lecture_tasks_path(params[:lecture_id]), method: :post do |f| %> 
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>
  </div> 
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

week11/CourseManagement/app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= form_for @task, url: lecture_task_path(params[:lecture_id], @task), method: :put do |f| %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>
  </div> 
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', lecture_tasks_path(params[:lecture_id]) %>

week11/CourseManagement/app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>List of all tasks for this lecture</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if @tasks.empty? %>
      <strong> No tasks yet </strong>
    <% else %>
      <% @tasks.each do |task| %>
        <tr>
          <td><%= task.name %></td>
          <td><%= link_to 'Show', lecture_task_path(params[:lecture_id], task) %></td>
          <td><%= link_to 'Edit', edit_lecture_task_path(params[:lecture_id], task) %></td>
          <td><%= link_to 'Destroy', lecture_task_path(params[:lecture_id], task), method: :delete, data: { confirm: 'Are you sure, you cannot restore it!!!' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_lecture_task_path(params[:lecture_id]) %>
<%= link_to 'Home Page', lectures_path %>

week11/CourseManagement/app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', lecture_tasks_path(params[:lecture_id]) %>

week11/CourseManagement/app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
    <%= @task.description %>
</p>

<%= link_to 'Edit', edit_lecture_task_path(params[:lecture_id], @task) %> |
<%= link_to 'Back', lecture_tasks_path(params[:lecture_id]) %>