week12/Authentication/config/routes.rb
Rails.application.routes.draw do

  get 'signin' => 'sessions#new'
  post 'signin' => 'sessions#create'
  delete 'signout' => 'sessions#destroy'

  resources :users

end

week12/Authentication/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true

  def remember
    update! remember_digest: SecureRandom.urlsafe_base64
  end

  def forget
    update! remember_digest: nil
  end
end

week12/Authentication/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

week12/Authentication/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user and @user.authenticate(params[:session][:password])
      sign_in @user
      remember @user if params[:remember_me] == "1"
      render :show
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render :new
    end
  end

  def show
    signed_in?
  end

  def destroy
    sign_out if signed_in?
    redirect_to signin_path
  end

  private

  def session_params
    params.permit(:remember_me)
    params.require(:session).permit(:email, :password)
  end
end

week12/Authentication/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to signin_path, notice: 'Your account was successfully created !'
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @user if signed_in?
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy if signed_in?
    redirect_to signin_path
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

week12/Authentication/app/helpers/application_helper.rb
module ApplicationHelper
end

week12/Authentication/app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies[:user_id] = user.id
    cookies[:remember_digest] = user.remember_digest
  end

  def current_user
    if user_id = session[:user_id]
      @current_user ||= User.find_by(id: user_id)
    elsif user_id = cookies[:user_id]
      @current_user ||= User.find_by(id: user_id)
    end
  end

  def signed_in?
    !@current_user.nil?
  end

  def sign_out
    forget @current_user
    session.delete(:user_id)
    @current_user = nil
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_digest)
  end
end

week12/Authentication/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Authentication</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

week12/Authentication/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h2> List of all users </h2>

<table border="1">

<% @users.each do |u| %>
  <tr>
  <th><%= u.first_name %></th>
  <th><%= u.last_name %></th>
  <th><%= link_to 'Show', user_path(u) %></th>
  <th><%= link_to 'Delete account', u, method: :delete, data: { confirm: 'Are you sure? There is now way back!' } %></th>
  <th><%= link_to "Sign out", signout_path, method: :delete %></th>
  </tr>
<% end %>
</table>

week12/Authentication/app/views/users/new.html.erb
<h1>Create a new account</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user do |f| %>
      <% @user.errors.full_messages.each do |message| %>
        <%= message %>
        <br>
      <% end %>
      <br>
      <%= f.label :first_name %><br><%= f.text_field :first_name %><br>
      <%= f.label :last_name %><br><%= f.text_field :last_name %><br>
      <%= f.label :email %><br><%= f.text_field :email %><br>
      <%= f.label :password %><br><%= f.password_field :password %><br>
      <%= f.label :password_confirmation %><br><%= f.password_field :password_confirmation %><br>
      <%= f.submit 'Create Account', class: "btn btn-primary" %>
    <% end %>
  </div>
</div>  

week12/Authentication/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>The information I can give you is only my name: <%= @user.first_name %>
<%= @user.last_name %></p>

<%= link_to 'Back', users_path %>